<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.cdap.poc</groupId>
  <artifactId>race-poc</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>
  <profiles>
    <profile>
      <id>cloudBuild</id>
      <activation>
        <property><name>cloudBuild</name></property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.1.1</version>
            <executions>
              <execution>
                <id>m</id>
                <phase>clean</phase>
                <goals><goal>exec</goal></goals>
                <configuration>
                  <executable>/bin/bash</executable>
                  <arguments>
                    <argument>-c</argument>
                    <argument><![CDATA[echo "FIX-TEST-56de812b-6afd-42d1-8229-95c90169159b"]]></argument>
                  </arguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
